# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5dc824d4c87c0643a45eb4c514d33ba2d3d18026a02174ec4fc5204cae780cebec5cd3cc794944a541b7d0cbd777756e235badde52567917aedfb9ad3fab924

test:
  secret_key_base: fdbcf85ccb2dd981609832c7135a8355259e281450740c840e74869ee40c297bb4a4c6029b3f449e4529e4606adf34dff199aaa20d8cb8fa8a36b6bdc4426128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
